[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
  environment = { VITE_SUPABASE_URL = "https://kxafjwhorihsvxtquovt.supabase.co", VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlhdCI6MTYyMTkzMzQ2MywiZXhwIjoxOTM3NTA5NDYzfQ.fglXVthzfOF5HmJLohM86BVWX4CL483cFnAH3jbKup4" }